//summary This program prints out lines of words to the screen. It's used to practice displaying information
//on the screen
//name: Jenna Wolf
//class: Fundamentals of Programming, CS155 - 01
//instructor: Dr. Art Kazmierczak
//date: 8/23/2023

public class Main
{
	public static void main(String[] args) 
	{
	    
		System.out.println("Welcome to CS-500");
		System.out.println("Welcome to Computer Science Department");
		System.out.println("Programming is fun");

	}
}

